name: munkipkg Build

on:
  workflow_dispatch: # manually triggered

jobs:
  munkipkg:
    runs-on: macos-latest
    timeout-minutes: 5 # Keeps your builds from running too long
    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d # Pin SHA1 hash instead of version
        with:
          lfs: true

      - name: Run munkipkg
        id: munkipkg
        uses: joncrain/munkipkg-action@v0.1

      - name: Echo
        run: |
          echo Tag: ${{ steps.munkipkg.outputs.tag }}
          echo File: ${{ steps.munkipkg.outputs.filename }}
          echo Path: ${{ steps.munkipkg.outputs.filepath }}
          echo ${{ steps.munkipkg.outputs.* }}
          echo ${{join(steps.munkipkg.outputs.*, '\n')}}

      - name: Create Release
        uses: softprops/action-gh-release@affa18ef97bc9db20076945705aba8c516139abd
        with:
          files: ${{ steps.munkipkg.outputs.filepath }}
          tag_name: ${{ steps.munkipkg.outputs.tag }}
